name: fizz-buzz-php
services:
  main:
    type: php:7.3
    build:
      - composer install
      - chmod +x ./bin/fizzbuzz
    overrides:
      environment:
        XTERM: xterm-256color
tooling:
  fizzbuzz:
    service: main
    cmd: ./bin/fizzbuzz
  composer:
    service: main
  lint:
    service: main
    cmd: composer exec phpcs
  test:
    service: main
    cmd: composer exec phpunit